apiVersion: skaffold/v1beta2
kind: Config
build:
  artifacts:
  - image: changeme
    context: .
    docker: {}
  tagPolicy:
    envTemplate:
      template: '{{.DOCKER_REGISTRY}}/shreya1396/python-docker:{{.VERSION}}'
  local: {}
deploy:
  kubectl: {}
profiles:
- name: dev
  build:
    artifacts:
    - docker: {}
    tagPolicy:
      envTemplate:
        template: '{{.DOCKER_REGISTRY}}/shreya1396/python-docker:{{.DIGEST_HEX}}'
    local: {}
  deploy:
    helm:
      releases:
      - name: python-docker
        chartPath: charts/python-docker
        setValueTemplates:
          image.repository: '{{.DOCKER_REGISTRY}}/shreya1396/python-docker'
          image.tag: '{{.DIGEST_HEX}}'
